name: ldls
channels:
  - defaults
dependencies:
  - _tflow_select=2.1.0=gpu
  - asn1crypto=0.24.0=py37_0
  - astor=0.7.1=py37_0
  - attrs=19.1.0=py37_1
  - backcall=0.1.0=py37_0
  - blas=1.0=mkl
  - c-ares=1.15.0=h7b6447c_1
  - ca-certificates=2019.1.23=0
  - certifi=2019.3.9=py37_0
  - cffi=1.12.2=py37h2e261b9_1
  - cloudpickle=0.8.1=py_0
  - cryptography=2.6.1=py37h1ba5d50_0
  - cudatoolkit=10.0.130=0
  - cudnn=7.3.1=cuda10.0_0
  - cupti=10.0.130=0
  - cupy=5.1.0=py37hc0ce245_0
  - cycler=0.10.0=py37_0
  - cytoolz=0.9.0.1=py37h14c3975_1
  - dask-core=1.2.0=py_0
  - dbus=1.13.6=h746ee38_0
  - decorator=4.4.0=py37_1
  - expat=2.2.6=he6710b0_0
  - fastrlock=0.4=py37he6710b0_0
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.9.1=h8a8886c_1
  - glib=2.56.2=hd408876_0
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - h5py=2.9.0=py37h7918eee_0
  - hdf5=1.10.4=hb1b8bf9_0
  - icu=58.2=h9c2bf20_1
  - imageio=2.5.0=py37_0
  - intel-openmp=2019.3=199
  - ipykernel=5.1.0=py37h39e3cac_0
  - ipython=7.4.0=py37h39e3cac_0
  - ipython_genutils=0.2.0=py37_0
  - jpeg=9b=h024ee3a_2
  - jupyter_client=5.2.4=py37_0
  - jupyter_core=4.4.0=py37_0
  - keras-applications=1.0.7=py_0
  - keras-preprocessing=1.0.9=py_0
  - kiwisolver=1.0.1=py37hf484d3e_0
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=8.2.0=hdf63c60_1
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.36=hbc83047_0
  - libprotobuf=3.7.1=hd408876_0
  - libsodium=1.0.16=h1bed415_0
  - libstdcxx-ng=8.2.0=hdf63c60_1
  - libtiff=4.0.10=h2733197_2
  - libuuid=1.0.3=h1bed415_2
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.9=he19cac6_0
  - llvmlite=0.28.0=py37hd408876_0
  - markdown=3.1=py37_0
  - matplotlib=3.0.3=py37h5429711_0
  - mkl=2019.3=199
  - mkl_fft=1.0.10=py37ha843d7b_0
  - mkl_random=1.0.2=py37hd81dba3_0
  - nbformat=4.4.0=py37_0
  - nccl=1.3.5=cuda10.0_0
  - ncurses=6.1=he6710b0_1
  - networkx=2.3=py_0
  - numba=0.43.1=py37h962f231_0
  - numpy=1.16.2=py37h7e9f1db_0
  - numpy-base=1.16.2=py37hde5b4d6_0
  - olefile=0.46=py37_0
  - openssl=1.1.1b=h7b6447c_1
  - pandas=0.24.2=py37he6710b0_0
  - parso=0.4.0=py_0
  - pbr=5.1.3=py_0
  - pcre=8.43=he6710b0_0
  - pexpect=4.7.0=py37_0
  - pillow=6.0.0=py37h34e0f95_0
  - pip=19.0.3=py37_0
  - plotly=3.7.0=py_0
  - prompt_toolkit=2.0.9=py37_0
  - pycparser=2.19=py37_0
  - pyopenssl=19.0.0=py37_0
  - pyparsing=2.4.0=py_0
  - pyqt=5.9.2=py37h05f1152_2
  - pyrsistent=0.14.11=py37h7b6447c_0
  - pysocks=1.6.8=py37_0
  - python=3.7.3=h0371630_0
  - python-dateutil=2.8.0=py37_0
  - pytz=2019.1=py_0
  - pywavelets=1.0.3=py37hdd07704_1
  - qt=5.9.7=h5867ecd_1
  - readline=7.0=h7b6447c_5
  - requests=2.21.0=py37_0
  - retrying=1.3.3=py37_2
  - scikit-image=0.14.2=py37he6710b0_0
  - scikit-learn=0.20.3=py37hd81dba3_0
  - scipy=1.2.1=py37h7c811a0_0
  - setuptools=41.0.0=py37_0
  - sip=4.19.8=py37hf484d3e_0
  - six=1.12.0=py37_0
  - sqlite=3.27.2=h7b6447c_0
  - tensorboard=1.13.1=py37hf484d3e_0
  - tensorflow=1.13.1=gpu_py37hc158e3b_0
  - tensorflow-base=1.13.1=gpu_py37h8d69cac_0
  - tensorflow-estimator=1.13.0=py_0
  - tensorflow-gpu=1.13.1=h0d30ee6_0
  - tk=8.6.8=hbc83047_0
  - toolz=0.9.0=py37_0
  - tornado=6.0.2=py37h7b6447c_0
  - traitlets=4.3.2=py37_0
  - werkzeug=0.15.2=py_0
  - wheel=0.33.1=py37_0
  - xz=5.2.4=h14c3975_4
  - zeromq=4.3.1=he6710b0_3
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0
  - pip:
    - absl-py==0.7.1
    - alabaster==0.7.12
    - babel==2.6.0
    - bleach==3.1.0
    - chardet==3.0.4
    - cython==0.29.7
    - defusedxml==0.6.0
    - docutils==0.14
    - entrypoints==0.3
    - gast==0.2.2
    - grpcio==1.20.0
    - idna==2.8
    - imagesize==1.1.0
    - imgaug==0.2.8
    - ipyparallel==6.2.3
    - ipython-genutils==0.2.0
    - ipywidgets==7.4.2
    - jedi==0.13.3
    - jinja2==2.10.1
    - jsonschema==3.0.1
    - jupyter==1.0.0
    - jupyter-console==6.0.0
    - keras==2.2.4
    - markupsafe==1.1.1
    - mistune==0.8.4
    - mock==2.0.0
    - mrcnn==0.2
    - nbconvert==5.4.1
    - nose==1.3.7
    - notebook==5.7.8
    - opencv-python==4.1.0.25
    - packaging==19.0
    - pandocfilters==1.4.2
    - pickleshare==0.7.5
    - pptk==0.1.0
    - prometheus-client==0.6.0
    - protobuf==3.7.1
    - ptyprocess==0.6.0
    - pycocotools==2.0.0
    - pygments==2.3.1
    - pyyaml==5.1
    - pyzmq==18.0.1
    - qtconsole==4.4.3
    - seaborn==0.9.0
    - send2trash==1.5.0
    - shapely==1.6.4.post2
    - snowballstemmer==1.2.1
    - sphinx==2.0.1
    - sphinxcontrib-applehelp==1.0.1
    - sphinxcontrib-devhelp==1.0.1
    - sphinxcontrib-htmlhelp==1.0.2
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==1.0.2
    - sphinxcontrib-serializinghtml==1.1.3
    - termcolor==1.1.0
    - terminado==0.8.2
    - testpath==0.4.2
    - urllib3==1.24.2
    - wcwidth==0.1.7
    - webencodings==0.5.1
    - widgetsnbextension==3.4.2
prefix: /home/bhw45/anaconda3/envs/ldls

